name: Allure Report

on:
  push:
  workflow_dispatch:
    inputs:
      ALLURE_JOB_RUN_ID:
        description: ALLURE_JOB_RUN_ID service parameter. Leave blank.
      ALLURE_USERNAME:
        description: ALLURE_USERNAME service parameter. Leave blank.

env:
    SOLUTION_FILE: Allure.Examples.NUnit3.sln
    BUILD_CONFIGURATION: Debug
    ALLURE_TOKEN: ${{ secrets.ALLURE_TOKEN }}
    ALLURE_JOB_RUN_ID: ${{ github.event.inputs.ALLURE_JOB_RUN_ID }}
    ALLURE_ENDPOINT: https://pavlovallureops.testops.cloud/
    ALLURE_PROJECT_ID: 34
    ALLURE_RESULTS: build/allure-results

jobs:
    autotests:
        name: Run tests and generate Allure Report
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
  
            - name: Set up .NET
              uses: actions/setup-dotnet@v3
              with:
                dotnet-version: |
                    7.0.x

            - name: Restore NuGet packages
              run: dotnet restore --packages .packages ${{ env.SOLUTION_FILE }}

            - name: Build solution
              run: dotnet build --no-restore --configuration ${{ env.BUILD_CONFIGURATION }} ${{ env.SOLUTION_FILE }}

            - name: Install allurectl
              uses: allure-framework/setup-allurectl@v1

            - name: Test solution
                
              run: allurectl watch -- dotnet test --no-build --configuration ${{ env.BUILD_CONFIGURATION }} ${{ env.SOLUTION_FILE }}
              env:
                ALLURE_RESULTS: /allure-results
              continue-on-error: true

