name: Allure Report

on:
  push:
    branches: ["testIT"]

env:
    SOLUTION_FILE: Allure.Examples.NUnit3.sln
    BUILD_CONFIGURATION: Debug
    ALLURE_RESULTS: build/allure-results

jobs:
    autotests:
        name: Run tests and generate Allure Report
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
  
            - name: Set up .NET
              uses: actions/setup-dotnet@v3
              with:
                dotnet-version: |
                    7.0.x

            - name: Restore NuGet packages
              run: dotnet restore --packages .packages ${{ env.SOLUTION_FILE }}

            - name: Build solution
              run: dotnet build --no-restore --configuration ${{ env.BUILD_CONFIGURATION }} ${{ env.SOLUTION_FILE }}

            - name: Test solution
                
              run: dotnet test --no-build --configuration ${{ env.BUILD_CONFIGURATION }} ${{ env.SOLUTION_FILE }}
              env:
                ALLURE_RESULTS: ${{ env.ALLURE_RESULTS }}
              continue-on-error: true

            - name: Submit results
              if: always()
              run: |
                pip install testit-cli
                export TMS_TOKEN=Wk1kYVNZdnpBMVFlcnpUQjZk
                testit results import -t Wk1kYVNZdnpBMVFlcnpUQjZk \
                  --url  https://team-nchk.testit.software\
                  --project-id 5236eb3f-7c05-46f9-a609-dc0278896464 \
                  --configuration-id 15dbb164-c1aa-4cbf-830c-8c01ae14f4fb \
                  --testrun-name "GitHub test run" \
                  --results results/test-results.xml

            - name: List Allure results
              run: tree -d / > tree 